// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tznvwmsgnyxysntyrise.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6bnZ3bXNnbnl4eXNudHlyaXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4MDU5NjYsImV4cCI6MjA0OTM4MTk2Nn0.w3Qon4HJG6ta0yQ5icInavNW_uqxrLDtGN1Wtwiq98s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);